# Uncomment the next line to define a global platform for your project
# platform :ios, '17.0.1'

target 'P3 iAd Execution' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for P3 iAd Execution
pod 'Google-Mobile-Ads-SDK'
  target 'P3 iAd ExecutionTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'P3 iAd ExecutionUITests' do
    # Pods for testing
  end

end
